// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdMDXMtkcDY_88HChqqrBNKGQcJ4-6J8s',
    appId: '1:837381877510:web:e6cbd7f18e35825ca6f887',
    messagingSenderId: '837381877510',
    projectId: 'flutter-learn-1e3db',
    authDomain: 'flutter-learn-1e3db.firebaseapp.com',
    storageBucket: 'flutter-learn-1e3db.appspot.com',
    measurementId: 'G-QGDRERHSS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlynwEg-1EFTnJPUBwRWHjTfugS2L6_Rc',
    appId: '1:837381877510:android:4874a5a8fcdde09ba6f887',
    messagingSenderId: '837381877510',
    projectId: 'flutter-learn-1e3db',
    storageBucket: 'flutter-learn-1e3db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYmLK3yRI_p18xu93xUsf7JqvCnB1WaUA',
    appId: '1:837381877510:ios:b3ed7213a916a276a6f887',
    messagingSenderId: '837381877510',
    projectId: 'flutter-learn-1e3db',
    storageBucket: 'flutter-learn-1e3db.appspot.com',
    iosBundleId: 'com.example.ayhaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYmLK3yRI_p18xu93xUsf7JqvCnB1WaUA',
    appId: '1:837381877510:ios:2669ca513fa576b4a6f887',
    messagingSenderId: '837381877510',
    projectId: 'flutter-learn-1e3db',
    storageBucket: 'flutter-learn-1e3db.appspot.com',
    iosBundleId: 'com.example.ayhaga.RunnerTests',
  );
}
